ADD an adapter to support Mariadb
tpope/vim-dadbod pull request #138
Opened 2023-07-25 13:24 UTC by hbarral

Hello! I'm not a Vim expert, although I'd like to contribute. It's not much, it's just a copy of what's already out there, I don't deserve any credit for that.

This `pull request` is intended to support Mariadb based on recent executable name changes.

2023-09-04 03:03 UTC, tpope requested changes
Needs to be added to the help file. Other than that this looks good to go.

2023-09-04 03:03 UTC, tpope commented on README.markdown
> +  - Mariadb
The correct spelling is "MariaDB".

2023-09-05 01:28 UTC, hbarral commented on README.markdown
> +  - Mariadb
It's already fixed, sir. Thank you!.

2023-10-03 07:13 UTC, boydbloemsma approved these changes

2023-10-03 07:14 UTC, boydbloemsma commented
Can this be merged?

2023-11-17 10:36 UTC, Askath commented
Would really love for this feature to be available soon

2024-01-17 07:34 UTC, raphaelladinig commented
would be really nice if this would be merged soon. Tested it on my system and it work 100%.

2024-02-15 10:10 UTC, Askath commented
Any info on this?

2024-02-16 01:20 UTC, merged